import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'sq' | 'bs' | 'en' | 'tr'; // Albanian, Bosnian, English, Turkish

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation data
const translations = {
  sq: {
    // Navigation
    'nav.about': 'Rreth Nesh',
    'nav.services': 'Shërbimet',
    'nav.contact': 'Kontakti',
    
    // Hero Section
    'hero.title': 'Laboratori Labor',
    'hero.subtitle': 'Analiza profesionale të gjakut dhe shërbime mjekësore me mbi 25 vjet eksperiencë dhe 500,000+ teste të kryera me 99.6% saktësi në Prizren',
    'hero.address': 'Gjeravica 30, Prizren 20000',
    'hero.hours': 'Hën-Premte 07:00-16:00 | Sht 07:00-13:00',
    'hero.hours.mobile': '07:00-16:00 (H-P) | 07:00-13:00 (Sht)',
    'hero.contact': 'Kontaktoni Tani',
    'hero.services': 'Shërbimet Tona',
    'hero.results247': 'Rezultatet elektronike 24/7 - Lexoni rezultatet tuaja kudo dhe kurdo',
    
    // About Section
    'about.title': 'Pse të Zgjidhni',
    'about.title.highlight': 'Laboratorin Labor',
    'about.description': 'Me mbi 25 vjet eksperiencë në fushën e analizave mjekësore, ne jemi partneri juaj i besueshëm për shëndetin dhe mirëqenien tuaj. Laboratori Labor ka kryer mbi 500,000 teste me 99.6% saktësi, duke ofruar shërbime të specializuara me teknologjinë më të re dhe stafin më të kualifikuar në Prizren.',
    'about.experience': '25+ Vjet Eksperiencë',
    'about.experience.desc': 'Dy dekadë shërbimi të besueshëm dhe profesional me mbi 500,000 teste të kryera me 99.6% saktësi',
    'about.security': 'Siguri dhe Cilësi',
    'about.security.desc': 'Përdorimi i teknologjisë më të avancuar dhe standardeve ndërkombëtare të sigurisë',
    'about.team': 'Staf i Kualifikuar',
    'about.team.desc': 'Ekip profesional i trajnuar me përvojë të gjatë në fushën e laboratorisë mjekësore',
    'about.speed': 'Rezultate të Shpejta',
    'about.speed.desc': 'Rezultate brenda disa orëve - përpunim dhe dorëzim i shpejtë me saktësi të lartë',
    'about.license': 'I Licensuar dhe i Certifikuar nga Autoritetet Shëndetësore të Kosovës',
    
    // Services Section
    'services.title': 'Shërbimet',
    'services.title.highlight': 'Tona',
    'services.description': 'Ofrojmë analizë të specializuara të gjakut dhe shërbime mjekësore me teknologjinë më të re, standardet më të larta të cilësisë dhe rezultate brenda disa orëve',
    'services.advanced.title': 'Analizat më të Avancuara të Gjakut',
    'services.advanced.description': 'Me teknologjinë më moderne dhe stafin më të kualifikuar, ne sigurojmë rezultate të sakta dhe të shpejta për të gjitha analizat e gjakut. Çdo test kryhet sipas standardeve ndërkombëtare dhe me kujdesin më të madh për detajet.',
    'services.online247': 'Rezultate Online 24/7',
    'services.online247.desc': 'Lexoni rezultatet tuaja në çdo kohë nga telefoni, tableti ose kompjuteri.',
    'services.tech': 'Teknologji e Re',
    'services.reports': 'Raporte të Detajuara',
    
    // Service Items
    'service.blood.title': 'Analiza e Gjakut të Plotë',
    'service.blood.desc': 'Analiza komplekse të gjakut që përfshijnë numërimin e qelizave, nivelet e hemoglobinës dhe parametra të tjerë të rëndësishëm',
    'service.cardiac.title': 'Profili Kardiak',
    'service.cardiac.desc': 'Teste specialë për vlerësimin e shëndetit të zemrës, kolesterolit dhe triglicerideve',
    'service.hormonal.title': 'Teste Hormonale',
    'service.hormonal.desc': 'Analiza të nivelit të hormoneve të ndryshme për diagnostikimin e çrregullimeve endokrine',
    'service.biochemistry.title': 'Biokimia Klinike',
    'service.biochemistry.desc': 'Analiza të enzimave, proteinave dhe substancave kimike në gjak për vlerësimin e funksionit të organeve',
    'service.infectious.title': 'Teste për Sëmundje Infektive',
    'service.infectious.desc': 'Diagnostikim i saktë për HIV, Hepatit A/B/C, dhe sëmundje të tjera infektive',
    'service.tumor.title': 'Markerë Tumoralë',
    'service.tumor.desc': 'Teste të specializuara për zbulimin e hershëm të kancerit dhe monitorimin e trajtimit',
    'service.allergy.title': 'Panele Alergjike',
    'service.allergy.desc': 'Identifikimi i alergjive të ndryshme për një jetë më të shëndetshme',
    'service.diabetes.title': 'Paneli i Diabetit',
    'service.diabetes.desc': 'HbA1c, toleranca e glukozës, nivelet e insulinës për menaxhimin e diabetit',
    'service.thyroid.title': 'Paneli i Plotë i Tiroideës',
    'service.thyroid.desc': 'TSH, T3, T4, antitrupat Anti-TPO për vlerësimin e plotë të tiroideës',
    'service.vitamin.title': 'Vitamina & Minerale',
    'service.vitamin.desc': 'B12, D3, Hekur, Folate dhe minerale të tjera thelbësore për shëndetin',
    'service.autoimmune.title': 'Sëmundje Autoimmune',
    'service.autoimmune.desc': 'ANA, RF, Anti-CCP dhe markerë të tjerë autoimmunë për diagnozë të saktë',
    'service.heavymetals.title': 'Metale të Rënda',
    'service.heavymetals.desc': 'Testim për plumb, merkur, kadmium dhe metale toksike të tjera',
    'service.urine.title': 'Analiza e Urinës',
    'service.urine.desc': 'Testim i plotë i urinës për vlerësimin e funksionit të veshkave, infeksioneve dhe çrregullimeve metabolike',
    'service.electronic.title': 'Rezultate Elektronike 24/7',
    'service.electronic.desc': 'Merrni rezultatet tuaja online në çdo kohë të ditës dhe natës, nga çdo pajisje me qasje në internet',
    'service.detailed.title': 'Raporte të Detajuara',
    'service.detailed.desc': 'Raporte të plota mjekësore me interpretim profesional dhe rekomandime për hapat e mëtejshëm',
    'services.more.title': 'Shërbime të Tjera',
    'services.more.description': 'Ofrojmë më shumë analiza dhe teste të specializuara sesa ato të listuara këtu. Për informacion të plotë mbi të gjitha shërbimet tona, na kontaktoni në WhatsApp, thirrje normale, mediat sociale ose vizitoni lokacionin tonë.',
    
    // Contact
    'contact.title': 'Kontaktoni',
    'contact.title.highlight': 'Me Ne',
    'contact.description': 'Jemi këtu për t\'ju ndihmuar me të gjitha pyetjet tuaja rreth shërbimeve tona mjekësore. Kontaktoni me ne për informata shtesë ose për të rezervuar një vizitë.',
    'contact.address': 'Adresa',
    'contact.phone': 'Telefoni',
    'contact.hours': 'Orari i Punës',
    'contact.email': 'Email',
    'contact.visit': 'Na Vizitoni në Laboratorin Tonë',
    'contact.visit.desc': 'Laboratori Labor ndodhet në qendër të Prizrenit, në një lokacion të lehtë për t\'u arritur. Ofrojmë një ambient të rehatshëm dhe profesional për të gjithë pacientët tanë.',
    'contact.phone.desc': 'Për informata dhe pyetje',
    'contact.email.desc': 'Për komunikim elektronik',
    'contact.closed': 'E mbyllur',
    'contact.parking': 'Parkingje i disponueshëm pranë laboratorit',
    'contact.call': 'Telefononi Tani',
    'contact.whatsapp': 'WhatsApp',
    'contact.directions': 'Merr Udhëzimet në Google Maps',
    
    // Working Hours
    'hours.weekdays': 'Hënë - Premte: 07:00 - 16:00',
    'hours.saturday': 'Shtunë: 07:00 - 13:00',
    'hours.sunday': 'E Diel: E mbyllur',
    'hours.short': 'Hënë-Premte: 07:00-16:00 | Shtunë: 07:00-13:00',
    
    // Technology Section
    'tech.title': 'Teknologjia më e',
    'tech.title.highlight': 'Avancuar',
    'tech.description': 'Investojmë në teknologjinë më të re nga kompanitë lider botërore për të siguruar rezultatet më të sakta dhe të shpejta për pacientët tanë',
    'tech.roche': 'Sisteme të avancuara për analizë biokimike dhe imunologjike',
    'tech.abbott': 'Teknologji moderne për diagnostikim të saktë dhe të shpejtë',
    'tech.siemens': 'Pajisje semi-automatike për rezultate të besueshme',
    'tech.sysmex': 'Teknologji lider botërore për analizën e gjakut dhe hematologji',
    'tech.quality': 'Kontroll i Cilësisë',
    'tech.quality.desc': 'Pjesëmarrje në programe ndërkombëtare të kontrollit të cilësisë',
    'tech.training': 'Trajnime Ndërkombëtare',
    'tech.training.desc': 'Stafi ynë merr pjesë rregullisht në trajnime ndërkombëtare',
    'tech.security': 'Siguri e Proceseve',
    'tech.security.desc': 'Procese të certifikuara të sigurimit të cilësisë dhe kalibrimit ditor',
    'tech.award': 'Teknologji e njëjtë e përdorur në spitalet më të mira evropiane',
    
    // Expert Team Section
    'team.title': 'Ekipi më i',
    'team.title.highlight': 'Kualifikuar',
    'team.description': 'Stafi ynë përbëhet nga mjekë dhe teknikë me kualifikime të larta dhe eksperiencë të gjatë në fushën e laboratorisë mjekësore',
    'team.experience': 'Mjekë dhe Teknikë me Eksperiencë',
    'team.experience.desc': 'Ekip i kvalifikuar mjekësor dhe teknikësh me dekada eksperiencë',
    'team.experience.detail': 'Shumica e stafit ka mbi 15 vjet eksperiencë',
    'team.international': 'Trajnime Ndërkombëtare',
    'team.international.desc': 'Pjesëmarrje e rregullt në trajnime dhe konferenca ndërkombëtare',
    'team.international.detail': 'Përditësim i vazhdueshëm i njohurive',
    'team.standards': 'Standarde Evropiane',
    'team.standards.desc': 'Zbatimi i protokolleve dhe standardeve evropiane të laboratorisë',
    'team.standards.detail': 'Cilësi në nivel me vendet e BE-së',
    'team.supervision': 'Mbikëqyrje Mjekësore',
    'team.supervision.desc': 'Të gjitha rezultatet rishikohen nga mjekë të specializuar',
    'team.supervision.detail': 'Kontroll i dyfishtë për saktësi maksimale',
    'team.certifications': 'Certifikime dhe Kualifikime',
    'team.certifications.desc': 'Investojmë vazhdimisht në arsimimin dhe trajnimin e stafit tonë për të siguruar që të jemi në hap me zhvillimet më të reja në mjekësi laboratorike.',
    'team.cert1': 'Kontroll i Cilësisë Ndërkombëtar',
    'team.cert2': 'Trajnime nga Roche Diagnostics',
    'team.cert3': 'Programe Siemens Healthineers',
    'team.cert4': 'Trajnime nga Sysmex Corporation',
    'team.expertise': 'Ekspertizë e Njohur',
    'team.expertise.desc': 'Laboratori ynë është i njohur në të gjithë rajonin për cilësinë e shërbimeve dhe ekspertizën e stafit.',
    'team.tests': 'Teste të Kryera',
    'team.accuracy': 'Saktësi në Rezultate',
    
    // Footer
    'footer.description': 'Me mbi 25 vjet eksperiencë në fushën e analizave mjekësore, Laboratori Labor është partneri juaj i besueshëm për shëndetin dhe mirëqenien tuaj në Prizren.',
    'footer.license': 'Licencuar nga Ministria e Shëndetësisë së Kosovës',
    'footer.copyright': '© 2024 Laboratori Labor. Të gjitha të drejtat e rezervuara.',
    'footer.design': 'Dizajni i faqes nga Lovable.',
    'footer.contact': 'Informata Kontakti',
    'footer.hours': 'Orari i Punës',
    'footer.follow': 'Na ndiqni',
    'footer.country': 'Republika e Kosovës',
    'footer.designed': 'Dizajnuar dhe zhvilluar me kujdes për pacientët tanë'
  },
  
  bs: {
    // Navigation
    'nav.about': 'O nama',
    'nav.services': 'Usluge',
    'nav.contact': 'Kontakt',
    
    // Hero Section
    'hero.title': 'Laboratorija Labor',
    'hero.subtitle': 'Profesionalne analize krvi i medicinske usluge sa preko 25 godina iskustva i 500,000+ testova izvršenih sa 99.6% tačnošću u Prizrenu',
    'hero.address': 'Đeravica 30, Prizren 20000',
    'hero.hours': 'Pon-Pet 07:00-16:00 | Sub 07:00-13:00',
    'hero.hours.mobile': '07:00-16:00 (P-P) | 07:00-13:00 (Sub)',
    'hero.contact': 'Kontaktirajte nas sada',
    'hero.services': 'Naše usluge',
    'hero.results247': 'Elektronski rezultati 24/7 - Čitajte rezultate bilo gde i bilo kada',
    
    // About Section
    'about.title': 'Zašto izabrati',
    'about.title.highlight': 'Laboratoriju Labor',
    'about.description': 'Sa preko 25 godina iskustva u oblasti medicinskih analiza, mi smo vaš pouzdan partner za zdravlje i blagostanje. Laboratorija Labor je izvršila preko 500,000 testova sa 99.6% tačnošću, pružajući specijalizovane usluge najnovijom tehnologijom i najkvalifikovanijim osobljem u Prizrenu.',
    'about.experience': '25+ godina iskustva',
    'about.experience.desc': 'Dve decenije pouzdane i profesionalne usluge sa preko 500,000 testova izvršenih sa 99.6% tačnošću',
    'about.security': 'Bezbednost i kvalitet',
    'about.security.desc': 'Korišćenje najnaprednijih tehnologija i međunarodnih standarda bezbednosti',
    'about.team': 'Kvalifikovano osoblje',
    'about.team.desc': 'Profesionalni tim obučen sa dugogodišnjim iskustvom u oblasti medicinske laboratorije',
    'about.speed': 'Brzi rezultati',
    'about.speed.desc': 'Rezultati u roku od nekoliko sati - brza obrada i isporuka sa visokom tačnošću',
    'about.license': 'Licenciran i sertifikovan od strane zdravstvenih vlasti Kosova',
    
    // Services Section
    'services.title': 'Naše',
    'services.title.highlight': 'usluge',
    'services.description': 'Pružamo specijalizovane analize krvi i medicinske usluge najnovijom tehnologijom, najvišim standardima kvaliteta i rezultatima u roku od nekoliko sati',
    'services.advanced.title': 'Najnaprednije analize krvi',
    'services.advanced.description': 'Najmodernijom tehnologijom i najkvalifikovanijim osobljem, garantujemo tačne i brze rezultate za sve analize krvi. Svaki test se izvršava prema međunarodnim standardima i najvećom pažnjom prema detaljima.',
    'services.online247': 'Online rezultati 24/7',
    'services.online247.desc': 'Čitajte rezultate bilo kada sa telefona, tableta ili računara.',
    'services.tech': 'Nova tehnologija',
    'services.reports': 'Detaljni izveštaji',
    
    // Service Items
    'service.blood.title': 'Kompletna analiza krvi',
    'service.blood.desc': 'Kompleksne analize krvi koje uključuju brojanje ćelija, nivoe hemoglobina i druge važne parametre',
    'service.cardiac.title': 'Srčani profil',
    'service.cardiac.desc': 'Specijalni testovi za procenu zdravlja srca, holesterola i triglicerida',
    'service.hormonal.title': 'Hormonski testovi',
    'service.hormonal.desc': 'Analize nivoa različitih hormona za dijagnostikovanje endokrinih poremećaja',
    'service.biochemistry.title': 'Klinička biohemija',
    'service.biochemistry.desc': 'Analize enzima, proteina i hemijskih supstanci u krvi za procenu funkcije organa',
    'service.infectious.title': 'Testovi za infektivne bolesti',
    'service.infectious.desc': 'Tačna dijagnoza za HIV, Hepatitis A/B/C i druge infektivne bolesti',
    'service.tumor.title': 'Tumorski markeri',
    'service.tumor.desc': 'Specijalizovani testovi za rano otkrivanje raka i praćenje lečenja',
    'service.allergy.title': 'Alergijski paneli',
    'service.allergy.desc': 'Identifikacija različitih alergija za zdraviji život',
    'service.diabetes.title': 'Panel za dijabetes',
    'service.diabetes.desc': 'HbA1c, test tolerancije glukoze, nivoi insulina za upravljanje dijabetesom',
    'service.thyroid.title': 'Kompletni tiroidni panel',
    'service.thyroid.desc': 'TSH, T3, T4, Anti-TPO antitela za potpunu procenu tiroide',
    'service.vitamin.title': 'Vitamini i minerali',
    'service.vitamin.desc': 'B12, D3, gvožđe, folat i drugi esencijalni minerali za zdravlje',
    'service.autoimmune.title': 'Autoimune bolesti',
    'service.autoimmune.desc': 'ANA, RF, Anti-CCP i drugi autoimuni markeri za tačnu dijagnozu',
    'service.heavymetals.title': 'Teški metali',
    'service.heavymetals.desc': 'Testiranje za olovo, živu, kadmijum i druge toksične metale',
    'service.urine.title': 'Analiza urina',
    'service.urine.desc': 'Kompletno testiranje urina za procenu bubrežne funkcije, infekcija i metaboličkih poremećaja',
    'service.electronic.title': 'Elektronski rezultati 24/7',
    'service.electronic.desc': 'Dobijte rezultate online bilo kada tokom dana i noći, sa bilo kog uređaja sa pristupom internetu',
    'service.detailed.title': 'Detaljni izveštaji',
    'service.detailed.desc': 'Kompletni medicinski izveštaji sa profesionalnim tumačenjem i preporukama za dalje korake',
    'services.more.title': 'Dodatne usluge',
    'services.more.description': 'Nudimo više analiza i specijalizovanih testova nego što su ovde navedeni. Za potpune informacije o svim našim uslugama, kontaktirajte nas preko WhatsApp-a, normalnog poziva, društvenih mreža ili posetite našu lokaciju.',
    
    // Contact
    'contact.title': 'Kontaktirajte',
    'contact.title.highlight': 'nas',
    'contact.description': 'Tu smo da vam pomognemo sa svim pitanjima o našim medicinskim uslugama. Kontaktirajte nas za dodatne informacije ili da zakažete posetu.',
    'contact.address': 'Adresa',
    'contact.phone': 'Telefon',
    'contact.hours': 'Radno vreme',
    'contact.email': 'Email',
    'contact.visit': 'Posetite nas u našoj laboratoriji',
    'contact.visit.desc': 'Laboratorija Labor se nalazi u centru Prizrena, na lako dostupnoj lokaciji. Pružamo udobnu i profesionalnu atmosferu za sve naše pacijente.',
    'contact.phone.desc': 'Za informacije i pitanja',
    'contact.email.desc': 'Za elektronsku komunikaciju',
    'contact.closed': 'Zatvoreno',
    'contact.parking': 'Parking dostupan pored laboratorije',
    'contact.call': 'Pozovite sada',
    'contact.whatsapp': 'WhatsApp',
    'contact.directions': 'Dobijte uputstva u Google Maps',
    
    // Working Hours
    'hours.weekdays': 'Ponedeljak - Petak: 07:00 - 16:00',
    'hours.saturday': 'Subota: 07:00 - 13:00',
    'hours.sunday': 'Nedelja: Zatvoreno',
    'hours.short': 'Ponedeljak-Petak: 07:00-16:00 | Subota: 07:00-13:00',
    
    // Technology Section
    'tech.title': 'Najnapredniju',
    'tech.title.highlight': 'Tehnologiju',
    'tech.description': 'Investiramo u najnoviju tehnologiju vodećih svetskih kompanija da bismo obezbedili najtačnije i najbrže rezultate za naše pacijente',
    'tech.roche': 'Napredni sistemi za biohemijske i imunološke analize',
    'tech.abbott': 'Moderna tehnologija za tačnu i brzu dijagnozu',
    'tech.siemens': 'Poluautomatski uređaji za pouzdane rezultate',
    'tech.sysmex': 'Vodeća svetska tehnologija za analizu krvi i hematologiju',
    'tech.quality': 'Kontrola kvaliteta',
    'tech.quality.desc': 'Učešće u međunarodnim programima kontrole kvaliteta',
    'tech.training': 'Međunarodna obuka',
    'tech.training.desc': 'Naše osoblje redovno učestvuje u međunarodnim obukama',
    'tech.security': 'Bezbednost procesa',
    'tech.security.desc': 'Sertifikovani procesi osiguranja kvaliteta i dnevne kalibracije',
    'tech.award': 'Ista tehnologija koja se koristi u najboljim evropskim bolnicama',
    
    // Expert Team Section
    'team.title': 'Najkvalifikovaniji',
    'team.title.highlight': 'Tim',
    'team.description': 'Naše osoblje se sastoji od lekara i tehničara sa visokim kvalifikacijama i dugogodišnjim iskustvom u oblasti medicinske laboratorije',
    'team.experience': 'Lekari i tehničari sa iskustvom',
    'team.experience.desc': 'Kvalifikovani tim lekara i tehničara sa decenijama iskustva',
    'team.experience.detail': 'Većina osoblja ima preko 15 godina iskustva',
    'team.international': 'Međunarodna obuka',
    'team.international.desc': 'Redovno učešće u međunarodnim obukama i konferencijama',
    'team.international.detail': 'Kontinuirane nadogradnje znanja',
    'team.standards': 'Evropski standardi',
    'team.standards.desc': 'Implementacija evropskih protokola i standarda laboratorije',
    'team.standards.detail': 'Kvalitet na nivou zemalja EU',
    'team.supervision': 'Medicinski nadzor',
    'team.supervision.desc': 'Sve rezultate pregledaju specijalizovani lekari',
    'team.supervision.detail': 'Dvostruka kontrola za maksimalnu tačnost',
    'team.certifications': 'Sertifikati i kvalifikacije',
    'team.certifications.desc': 'Kontinuirano investiramo u obrazovanje i obuku našeg osoblja da bismo osigurali da smo u koraku sa najnovijim razvojima u laboratorijskoj medicini.',
    'team.cert1': 'Međunarodna kontrola kvaliteta',
    'team.cert2': 'Obuka Roche Diagnostics',
    'team.cert3': 'Siemens Healthineers programi',
    'team.cert4': 'Obuka Sysmex Corporation',
    'team.expertise': 'Priznata stručnost',
    'team.expertise.desc': 'Naša laboratorija je poznata u celom regionu po kvalitetu usluga i stručnosti osoblja.',
    'team.tests': 'Izvršenih testova',
    'team.accuracy': 'Tačnost rezultata',
    
    // Footer
    'footer.description': 'Sa preko 25 godina iskustva u oblasti medicinskih analiza, Laboratorija Labor je vaš pouzdan partner za zdravlje i blagostanje u Prizrenu.',
    'footer.license': 'Licenciran od strane Ministarstva zdravlja Kosova',
    'footer.copyright': '© 2024 Laboratorija Labor. Sva prava zadržana.',
    'footer.design': 'Dizajn stranice od Lovable.',
    'footer.contact': 'Informacije o kontaktu',
    'footer.hours': 'Radno vreme',
    'footer.follow': 'Pratite nas',
    'footer.country': 'Republika Kosovo',
    'footer.designed': 'Dizajnirano i razvijeno s pažnjom za naše pacijente'
  },
  
  en: {
    // Navigation
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    
    // Hero Section
    'hero.title': 'Laboratory Labor',
    'hero.subtitle': 'Professional blood analysis and medical services with over 25 years of experience and 500,000+ tests performed with 99.6% accuracy in Prizren',
    'hero.address': 'Gjeravica 30, Prizren 20000',
    'hero.hours': 'Mon-Fri 07:00-16:00 | Sat 07:00-13:00',
    'hero.hours.mobile': '07:00-16:00 (M-F) | 07:00-13:00 (Sat)',
    'hero.contact': 'Contact Us Now',
    'hero.services': 'Our Services',
    'hero.results247': 'Electronic results 24/7 - Read your results anywhere, anytime',
    
    // About Section
    'about.title': 'Why Choose',
    'about.title.highlight': 'Laboratory Labor',
    'about.description': 'With over 25 years of experience in medical analysis, we are your trusted partner for health and wellness. Laboratory Labor has performed over 500,000 tests with 99.6% accuracy, providing specialized services with the latest technology and the most qualified staff in Prizren.',
    'about.experience': '25+ Years of Experience',
    'about.experience.desc': 'Two decades of reliable and professional service with over 500,000 tests performed with 99.6% accuracy',
    'about.security': 'Security and Quality',
    'about.security.desc': 'Using the most advanced technology and international safety standards',
    'about.team': 'Qualified Staff',
    'about.team.desc': 'Professional team trained with extensive experience in the medical laboratory field',
    'about.speed': 'Fast Results',
    'about.speed.desc': 'Results within hours - fast processing and delivery with high accuracy',
    'about.license': 'Licensed and Certified by Kosovo Health Authorities',
    
    // Services Section
    'services.title': 'Our',
    'services.title.highlight': 'Services',
    'services.description': 'We provide specialized blood analysis and medical services with the latest technology, highest quality standards, and results within hours',
    'services.advanced.title': 'Most Advanced Blood Analysis',
    'services.advanced.description': 'With the most modern technology and qualified staff, we ensure accurate and fast results for all blood analyses. Every test is performed according to international standards and with the greatest attention to detail.',
    'services.online247': 'Online Results 24/7',
    'services.online247.desc': 'Read your results anytime from phone, tablet, or computer.',
    'services.tech': 'New Technology',
    'services.reports': 'Detailed Reports',
    
    // Service Items
    'service.blood.title': 'Complete Blood Analysis',
    'service.blood.desc': 'Comprehensive blood tests including cell count, hemoglobin levels, and other important parameters',
    'service.cardiac.title': 'Cardiac Profile',
    'service.cardiac.desc': 'Special tests for heart health assessment, cholesterol, and triglycerides',
    'service.hormonal.title': 'Hormonal Tests',
    'service.hormonal.desc': 'Analysis of various hormone levels for diagnosing endocrine disorders',
    'service.biochemistry.title': 'Clinical Biochemistry',
    'service.biochemistry.desc': 'Analysis of enzymes, proteins, and chemical substances in blood for organ function assessment',
    'service.infectious.title': 'Infectious Disease Tests',
    'service.infectious.desc': 'Accurate diagnosis for HIV, Hepatitis A/B/C, and other infectious diseases',
    'service.tumor.title': 'Tumor Markers',
    'service.tumor.desc': 'Specialized tests for early cancer detection and treatment monitoring',
    'service.allergy.title': 'Allergy Panels',
    'service.allergy.desc': 'Identification of various allergies for a healthier life',
    'service.diabetes.title': 'Diabetes Management Panel',
    'service.diabetes.desc': 'HbA1c, glucose tolerance, insulin levels for comprehensive diabetes management',
    'service.thyroid.title': 'Complete Thyroid Panel',
    'service.thyroid.desc': 'TSH, T3, T4, Anti-TPO antibodies for comprehensive thyroid assessment',
    'service.vitamin.title': 'Vitamin & Mineral Panel',
    'service.vitamin.desc': 'B12, D3, Iron, Folate and other essential minerals for optimal health',
    'service.autoimmune.title': 'Autoimmune Disease Testing',
    'service.autoimmune.desc': 'ANA, RF, Anti-CCP and other autoimmune markers for accurate diagnosis',
    'service.heavymetals.title': 'Heavy Metal Screening',
    'service.heavymetals.desc': 'Testing for lead, mercury, cadmium and other toxic metals',
    'service.urine.title': 'Urine Analysis',
    'service.urine.desc': 'Complete urine testing for kidney function assessment, infections, and metabolic disorders',
    'service.electronic.title': 'Electronic Results 24/7',
    'service.electronic.desc': 'Get your results online anytime day or night, from any device with internet access',
    'service.detailed.title': 'Detailed Reports',
    'service.detailed.desc': 'Complete medical reports with professional interpretation and recommendations for next steps',
    'services.more.title': 'Additional Services',
    'services.more.description': 'We offer more analyses and specialized tests than those listed here. For complete information about all our services, contact us on WhatsApp, normal call, social media, or visit our location.',
    
    // Contact
    'contact.title': 'Contact',
    'contact.title.highlight': 'Us',
    'contact.description': 'We are here to help you with all your questions about our medical services. Contact us for additional information or to schedule a visit.',
    'contact.address': 'Address',
    'contact.phone': 'Phone',
    'contact.hours': 'Working Hours',
    'contact.email': 'Email',
    'contact.visit': 'Visit Us at Our Laboratory',
    'contact.visit.desc': 'Laboratory Labor is located in the center of Prizren, in an easily accessible location. We provide a comfortable and professional environment for all our patients.',
    'contact.phone.desc': 'For information and questions',
    'contact.email.desc': 'For electronic communication',
    'contact.closed': 'Closed',
    'contact.parking': 'Parking available near the laboratory',
    'contact.call': 'Call Now',
    'contact.whatsapp': 'WhatsApp',
    'contact.directions': 'Get Directions on Google Maps',
    
    // Working Hours
    'hours.weekdays': 'Monday - Friday: 07:00 - 16:00',
    'hours.saturday': 'Saturday: 07:00 - 13:00',
    'hours.sunday': 'Sunday: Closed',
    'hours.short': 'Monday-Friday: 07:00-16:00 | Saturday: 07:00-13:00',
    
    // Technology Section
    'tech.title': 'Most Advanced',
    'tech.title.highlight': 'Technology',
    'tech.description': 'We invest in the latest technology from leading global companies to ensure the most accurate and fast results for our patients',
    'tech.roche': 'Advanced systems for biochemical and immunological analysis',
    'tech.abbott': 'Modern technology for accurate and fast diagnosis',
    'tech.siemens': 'Semi-automatic devices for reliable results',
    'tech.sysmex': 'World-leading technology for blood analysis and hematology',
    'tech.quality': 'Quality Control',
    'tech.quality.desc': 'Participation in international quality control programs',
    'tech.training': 'International Training',
    'tech.training.desc': 'Our staff regularly participates in international training',
    'tech.security': 'Process Security',
    'tech.security.desc': 'Certified quality assurance processes and daily calibration',
    'tech.award': 'Same technology used in the best European hospitals',
    
    // Expert Team Section
    'team.title': 'Most Qualified',
    'team.title.highlight': 'Team',
    'team.description': 'Our staff consists of doctors and technicians with high qualifications and extensive experience in the medical laboratory field',
    'team.experience': 'Doctors and Technicians with Experience',
    'team.experience.desc': 'Qualified team of doctors and technicians with decades of experience',
    'team.experience.detail': 'Most of the staff has over 15 years of experience',
    'team.international': 'International Training',
    'team.international.desc': 'Regular participation in international training and conferences',
    'team.international.detail': 'Continuous knowledge updates',
    'team.standards': 'European Standards',
    'team.standards.desc': 'Implementation of European laboratory protocols and standards',
    'team.standards.detail': 'Quality at the level of EU countries',
    'team.supervision': 'Medical Supervision',
    'team.supervision.desc': 'All results are reviewed by specialized doctors',
    'team.supervision.detail': 'Double control for maximum accuracy',
    'team.certifications': 'Certifications and Qualifications',
    'team.certifications.desc': 'We continuously invest in education and training of our staff to ensure we are in step with the latest developments in laboratory medicine.',
    'team.cert1': 'International Quality Control',
    'team.cert2': 'Roche Diagnostics Training',
    'team.cert3': 'Siemens Healthineers Programs',
    'team.cert4': 'Sysmex Corporation Training',
    'team.expertise': 'Recognized Expertise',
    'team.expertise.desc': 'Our laboratory is known throughout the region for the quality of services and staff expertise.',
    'team.tests': 'Tests Performed',
    'team.accuracy': 'Accuracy in Results',
    
    // Footer
    'footer.description': 'With over 25 years of experience in medical analysis, Laboratory Labor is your trusted partner for health and wellness in Prizren.',
    'footer.license': 'Licensed by the Ministry of Health of Kosovo',
    'footer.copyright': '© 2024 Laboratory Labor. All rights reserved.',
    'footer.design': 'Website design by Lovable.',
    'footer.contact': 'Contact Information',
    'footer.hours': 'Working Hours',
    'footer.follow': 'Follow us',
    'footer.country': 'Republic of Kosovo',
    'footer.designed': 'Designed and developed with care for our patients'
  },
  
  tr: {
    // Navigation
    'nav.about': 'Hakkımızda',
    'nav.services': 'Hizmetler',
    'nav.contact': 'İletişim',
    
    // Hero Section
    'hero.title': 'Laboratuvar Labor',
    'hero.subtitle': '25 yılı aşkın deneyim ve Prizren\'de 500.000+ test ile %99.6 doğruluk oranında profesyonel kan analizi ve tıbbi hizmetler',
    'hero.address': 'Gjeravica 30, Prizren 20000',
    'hero.hours': 'Pzt-Cum 07:00-16:00 | Cmt 07:00-13:00',
    'hero.hours.mobile': '07:00-16:00 (P-C) | 07:00-13:00 (Cmt)',
    'hero.contact': 'Şimdi İletişime Geçin',
    'hero.services': 'Hizmetlerimiz',
    'hero.results247': 'Elektronik sonuçlar 7/24 - Sonuçlarınızı her yerden, her zaman okuyun',
    
    // About Section
    'about.title': 'Neden',
    'about.title.highlight': 'Laboratuvar Labor\'u Seçmelisiniz',
    'about.description': 'Tıbbi analiz alanında 25 yılı aşkın deneyimimizle, sağlık ve refah konularında güvenilir ortağınızız. Laboratuvar Labor, Prizren\'de en son teknoloji ve en nitelikli personelle %99.6 doğruluk oranında 500.000\'den fazla test gerçekleştirmiş, uzmanlaşmış hizmetler sunmaktadır.',
    'about.experience': '25+ Yıl Deneyim',
    'about.experience.desc': 'İki onluk yıl güvenilir ve profesyonel hizmet ile %99.6 doğruluk oranında 500.000\'den fazla test',
    'about.security': 'Güvenlik ve Kalite',
    'about.security.desc': 'En gelişmiş teknoloji ve uluslararası güvenlik standartlarının kullanımı',
    'about.team': 'Nitelikli Personel',
    'about.team.desc': 'Tıbbi laboratuvar alanında uzun deneyime sahip eğitimli profesyonel ekip',
    'about.speed': 'Hızlı Sonuçlar',
    'about.speed.desc': 'Saatler içinde sonuç - yüksek doğrulukla hızlı işleme ve teslimat',
    'about.license': 'Kosova Sağlık Otoriteleri Tarafından Lisanslanmış ve Sertifikalandırılmış',
    
    // Services Section
    'services.title': 'Bizim',
    'services.title.highlight': 'Hizmetlerimiz',
    'services.description': 'En son teknoloji, en yüksek kalite standartları ve saatler içinde sonuçlarla uzmanlaşmış kan analizi ve tıbbi hizmetler sunuyoruz',
    'services.advanced.title': 'En Gelişmiş Kan Analizi',
    'services.advanced.description': 'En modern teknoloji ve nitelikli personelle, tüm kan analizleri için doğru ve hızlı sonuçlar garanti ediyoruz. Her test uluslararası standartlara göre ve detaylara en büyük özenle yapılır.',
    'services.online247': 'Online Sonuçlar 7/24',
    'services.online247.desc': 'Sonuçlarınızı telefon, tablet veya bilgisayardan istediğiniz zaman okuyun.',
    'services.tech': 'Yeni Teknoloji',
    'services.reports': 'Detaylı Raporlar',
    
    // Service Items
    'service.blood.title': 'Tam Kan Analizi',
    'service.blood.desc': 'Hücre sayımı, hemoglobin seviyeleri ve diğer önemli parametreleri içeren kapsamlı kan testleri',
    'service.cardiac.title': 'Kardiyak Profil',
    'service.cardiac.desc': 'Kalp sağlığı, kolesterol ve trigliserit değerlendirmesi için özel testler',
    'service.hormonal.title': 'Hormonal Testler',
    'service.hormonal.desc': 'Endokrin bozuklukların teşhisi için çeşitli hormon seviyelerinin analizi',
    'service.biochemistry.title': 'Klinik Biyokimya',
    'service.biochemistry.desc': 'Organ fonksiyonu değerlendirmesi için kandaki enzim, protein ve kimyasal maddelerin analizi',
    'service.infectious.title': 'Enfeksiyöz Hastalık Testleri',
    'service.infectious.desc': 'HIV, Hepatit A/B/C ve diğer enfeksiyöz hastalıklar için doğru teşhis',
    'service.tumor.title': 'Tümör Belirteçleri',
    'service.tumor.desc': 'Erken kanser tespiti ve tedavi takibi için uzmanlaşmış testler',
    'service.allergy.title': 'Alerji Panelleri',
    'service.allergy.desc': 'Daha sağlıklı bir yaşam için çeşitli alerjilerin tanımlanması',
    'service.diabetes.title': 'Diyabet Yönetim Paneli',
    'service.diabetes.desc': 'Kapsamlı diyabet yönetimi için HbA1c, glukoz toleransı, insülin seviyeleri',
    'service.thyroid.title': 'Komplet Tiroid Paneli',
    'service.thyroid.desc': 'Kapsamlı tiroid değerlendirmesi için TSH, T3, T4, Anti-TPO antikorları',
    'service.vitamin.title': 'Vitamin ve Mineral Paneli',
    'service.vitamin.desc': 'Optimal sağlık için B12, D3, Demir, Folat ve diğer esansiyel mineraller',
    'service.autoimmune.title': 'Otoimmün Hastalık Testleri',
    'service.autoimmune.desc': 'Doğru teşhis için ANA, RF, Anti-CCP ve diğer otoimmün belirteçler',
    'service.heavymetals.title': 'Ağır Metal Taraması',
    'service.heavymetals.desc': 'Kurşun, cıva, kadmiyum ve diğer toksik metallerin testleri',
    'service.urine.title': 'İdrar Analizi',
    'service.urine.desc': 'Böbrek fonksiyonu değerlendirmesi, enfeksiyonlar ve metabolik bozukluklar için eksiksiz idrar testi',
    'service.electronic.title': 'Elektronik Sonuçlar 7/24',
    'service.electronic.desc': 'Sonuçlarınızı gece gündüz internet erişimi olan herhangi bir cihazdan online alın',
    'service.detailed.title': 'Detaylı Raporlar',
    'service.detailed.desc': 'Profesyonel yorumlama ve sonraki adımlar için önerilerle eksiksiz tıbbi raporlar',
    'services.more.title': 'Ek Hizmetler',
    'services.more.description': 'Burada listelenenlerden daha fazla analiz ve uzman testler sunuyoruz. Tüm hizmetlerimiz hakkında tam bilgi için WhatsApp, normal arama, sosyal medya üzerinden bize ulaşın veya lokasyonumuzu ziyaret edin.',
    
    // Contact
    'contact.title': 'Bizimle',
    'contact.title.highlight': 'İletişime Geçin',
    'contact.description': 'Tıbbi hizmetlerimizle ilgili tüm sorularınızda size yardımcı olmak için buradayız. Ek bilgi almak veya randevu almak için bizimle iletişime geçin.',
    'contact.address': 'Adres',
    'contact.phone': 'Telefon',
    'contact.hours': 'Çalışma Saatleri',
    'contact.email': 'E-posta',
    'contact.visit': 'Laboratuvarımızı Ziyaret Edin',
    'contact.visit.desc': 'Laboratuvar Labor, Prizren merkezinde, kolayca ulaşılabilir bir konumda yer almaktadır. Tüm hastalarımız için rahat ve profesyonel bir ortam sağlıyoruz.',
    'contact.phone.desc': 'Bilgi ve sorular için',
    'contact.email.desc': 'Elektronik iletişim için',
    'contact.closed': 'Kapalı',
    'contact.parking': 'Laboratuvar yakınında park yeri mevcuttur',
    'contact.call': 'Şimdi Arayın',
    'contact.whatsapp': 'WhatsApp',
    'contact.directions': 'Google Maps\'te Yol Tarifi Alın',
    
    // Working Hours
    'hours.weekdays': 'Pazartesi - Cuma: 07:00 - 16:00',
    'hours.saturday': 'Cumartesi: 07:00 - 13:00',
    'hours.sunday': 'Pazar: Kapalı',
    'hours.short': 'Pazartesi-Cuma: 07:00-16:00 | Cumartesi: 07:00-13:00',
    
    // Technology Section
    'tech.title': 'En Gelişmiş',
    'tech.title.highlight': 'Teknoloji',
    'tech.description': 'Hastalarımız için en doğru ve hızlı sonuçları sağlamak için önde gelen küresel şirketlerden en son teknolojiye yatırım yapıyoruz',
    'tech.roche': 'Biyokimyasal ve immünolojik analiz için gelişmiş sistemler',
    'tech.abbott': 'Doğru ve hızlı teşhis için modern teknoloji',
    'tech.siemens': 'Güvenilir sonuçlar için yarı otomatik cihazlar',
    'tech.sysmex': 'Kan analizi ve hematoloji için dünya lideri teknoloji',
    'tech.quality': 'Kalite Kontrol',
    'tech.quality.desc': 'Uluslararası kalite kontrol programlarına katılım',
    'tech.training': 'Uluslararası Eğitim',
    'tech.training.desc': 'Personelimiz düzenli olarak uluslararası eğitimlere katılır',
    'tech.security': 'Süreç Güvenliği',
    'tech.security.desc': 'Sertifikalı kalite güvence süreçleri ve günlük kalibrasyon',
    'tech.award': 'En iyi Avrupa hastanelerinde kullanılan aynı teknoloji',
    
    // Expert Team Section
    'team.title': 'En Nitelikli',
    'team.title.highlight': 'Ekip',
    'team.description': 'Personelimiz, tıbbi laboratuvar alanında yüksek nitelikler ve uzun deneyime sahip doktor ve teknisyenlerden oluşmaktadır',
    'team.experience': 'Deneyimli Doktor ve Teknisyenler',
    'team.experience.desc': 'Onlarca yıllık deneyime sahip nitelikli doktor ve teknisyen ekibi',
    'team.experience.detail': 'Personelin çoğu 15 yıldan fazla deneyime sahiptir',
    'team.international': 'Uluslararası Eğitim',
    'team.international.desc': 'Uluslararası eğitim ve konferanslara düzenli katılım',
    'team.international.detail': 'Sürekli bilgi güncellemeleri',
    'team.standards': 'Avrupa Standartları',
    'team.standards.desc': 'Avrupa laboratuvar protokol ve standartlarının uygulanması',
    'team.standards.detail': 'AB ülkeleri seviyesinde kalite',
    'team.supervision': 'Tıbbi Denetim',
    'team.supervision.desc': 'Tüm sonuçlar uzman doktorlar tarafından gözden geçirilir',
    'team.supervision.detail': 'Maksimum doğruluk için çifte kontrol',
    'team.certifications': 'Sertifikalar ve Nitelikler',
    'team.certifications.desc': 'Laboratuvar tıbbındaki en son gelişmelere ayak uydurmamızı sağlamak için personelimizin eğitim ve öğretimine sürekli yatırım yapıyoruz.',
    'team.cert1': 'Uluslararası Kalite Kontrol',
    'team.cert2': 'Roche Diagnostics Eğitimi',
    'team.cert3': 'Siemens Healthineers Programları',
    'team.cert4': 'Sysmex Corporation Eğitimi',
    'team.expertise': 'Tanınmış Uzmanlık',
    'team.expertise.desc': 'Laboratuvarımız bölgede hizmet kalitesi ve personel uzmanlığı ile tanınmaktadır.',
    'team.tests': 'Yapılan Testler',
    'team.accuracy': 'Sonuç Doğruluğu',
    
    // Footer
    'footer.description': '25 yılı aşkın deneyimle tıbbi analiz alanında Laboratuvar Labor, sağlık ve refah konularında Prizren\'de güvenilir ortağınızdır.',
    'footer.license': 'Kosova Sağlık Bakanlığı Tarafından Lisanslanmıştır',
    'footer.copyright': '© 2024 Laboratuvar Labor. Tüm hakları saklıdır.',
    'footer.design': 'Web sitesi tasarımı Lovable tarafından yapılmıştır.',
    'footer.contact': 'İletişim Bilgileri',
    'footer.hours': 'Çalışma Saatleri',
    'footer.follow': 'Bizi takip edin',
    'footer.country': 'Kosova Cumhuriyeti',
    'footer.designed': 'Hastalarımız için özenle tasarlanmış ve geliştirilmiştir'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('sq'); // Default to Albanian

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
